### ISSUE TITLE
[maintenance] Upgrade to work with openwisp-controller 0.8

### ISSUE THREAD

**Issue by nemesifier** [openwisp/django-owm-legacy#5]
Upgrade the code to make it work with openwisp-controller 0.8 and django 3.1.
Update openwisp-utils test dependency.
Then release a new version (0.5).

**Comment by NoumbissiValere** [comment]
@nemesisdesign should all the modules of `openwisp_controller` be imported or just `openwisp_controller.config` and `openwisp_controller.pki`?

**Comment by nemesifier** [comment]
> @nemesisdesign should all the modules of `openwisp_controller` be imported or just `openwisp_controller.config` and `openwisp_controller.pki`?

Better test it with all the modules enabled, to ensure there's no incompatible code.
But the code which will be used will be only `openwisp_controller.config`.

PS: please keep in mind that the README will have to be updated as well.
