### ISSUE TITLE
[tests] Ensure openwisp-controller 1.0.x runs in tests

### ISSUE THREAD

**Issue by nemesifier** [openwisp/django-owm-legacy#7]
Ensure openwisp-controller 1.0.x runs in tests.

**Comment by pandafy** [comment]
This project is using openwisp-controller available on PyPI. 
https://github.com/openwisp/django-owm-legacy/blob/8dc2130dc2755a3bfa4500f39c768b4a497294c7/requirements.txt#L1

Should I update it to install latest master?

**Comment by nemesifier** [comment]
> This project is using openwisp-controller available on PyPI.
> 
> https://github.com/openwisp/django-owm-legacy/blob/8dc2130dc2755a3bfa4500f39c768b4a497294c7/requirements.txt#L1
> 
> Should I update it to install latest master?

Yes please.
